----- NEW RUN -----poisoningyou429 Client Error: Too Many Requests for url: https://na1.api.riotgames.com/lol/summoner/v4/summoners/by-name/poisoningyou
Traceback (most recent call last):
  File "fetcher.py", line 221, in <module>
    fetchGames(n)
  File "fetcher.py", line 48, in fetchGames
    targetId = watcher.summoner.by_name(REGION_NA, summonerName)["accountId"]
  File "/usr/local/lib/python3.7/site-packages/riotwatcher/_apis/SummonerApiV4.py", line 46, in by_name
    return self._raw_request(self.by_name.__name__, region, url, query)
  File "/usr/local/lib/python3.7/site-packages/riotwatcher/_apis/NamedEndpoint.py", line 29, in _raw_request
    self._endpoint_name, method_name, region, url, query_params
  File "/usr/local/lib/python3.7/site-packages/riotwatcher/_apis/BaseApi.py", line 23, in raw_request
    region, endpoint_name, method_name, url, query_params
  File "/usr/local/lib/python3.7/site-packages/riotwatcher/Handlers/RateLimit/RateLimitHandler.py", line 52, in preview_request
    time.sleep(to_wait.total_seconds())
KeyboardInterrupt
       87.97 real         0.91 user         0.14 sys
